// Nifty 50 constituent Yahoo Finance symbols (NSE: .NS suffix)
export const NIFTY50_SYMBOLS: Array<{ symbol: string; name: string }> = [
	{ symbol: 'RELIANCE.NS', name: 'Reliance' },
	{ symbol: 'TCS.NS', name: 'TCS' },
	{ symbol: 'HDFCBANK.NS', name: 'HDFC Bank' },
	{ symbol: 'BHARTIARTL.NS', name: 'Airtel' },
	{ symbol: 'ICICIBANK.NS', name: 'ICICI Bank' },
	{ symbol: 'INFY.NS', name: 'Infosys' },
	{ symbol: 'SBIN.NS', name: 'SBI' },
	{ symbol: 'LT.NS', name: 'L&T' },
	{ symbol: 'HINDUNILVR.NS', name: 'HUL' },
	{ symbol: 'BAJFINANCE.NS', name: 'Bajaj Finance' },
	{ symbol: 'KOTAKBANK.NS', name: 'Kotak Bank' },
	{ symbol: 'HCLTECH.NS', name: 'HCL Tech' },
	{ symbol: 'MARUTI.NS', name: 'Maruti' },
	{ symbol: 'AXISBANK.NS', name: 'Axis Bank' },
	{ symbol: 'TITAN.NS', name: 'Titan' },
	{ symbol: 'ASIANPAINT.NS', name: 'Asian Paints' },
	{ symbol: 'WIPRO.NS', name: 'Wipro' },
	{ symbol: 'ADANIENT.NS', name: 'Adani Ent.' },
	{ symbol: 'ADANIPORTS.NS', name: 'Adani Ports' },
	{ symbol: 'SUNPHARMA.NS', name: 'Sun Pharma' },
	{ symbol: 'ULTRACEMCO.NS', name: 'UltraTech' },
	{ symbol: 'POWERGRID.NS', name: 'Power Grid' },
	{ symbol: 'NTPC.NS', name: 'NTPC' },
	{ symbol: 'ONGC.NS', name: 'ONGC' },
	{ symbol: 'BAJAJFINSV.NS', name: 'Bajaj Finserv' },
	{ symbol: 'JSWSTEEL.NS', name: 'JSW Steel' },
	{ symbol: 'TATACONSUM.NS', name: 'Tata Consumer' },
	{ symbol: 'TATAMOTORS.NS', name: 'Tata Motors' },
	{ symbol: 'ITC.NS', name: 'ITC' },
	{ symbol: 'COALINDIA.NS', name: 'Coal India' },
	{ symbol: 'TATASTEEL.NS', name: 'Tata Steel' },
	{ symbol: 'TECHM.NS', name: 'Tech Mahindra' },
	{ symbol: 'M&M.NS', name: 'M&M' },
	{ symbol: 'NESTLEIND.NS', name: 'Nestle India' },
	{ symbol: 'APOLLOHOSP.NS', name: 'Apollo Hospitals' },
	{ symbol: 'BPCL.NS', name: 'BPCL' },
	{ symbol: 'DRREDDY.NS', name: "Dr Reddy's" },
	{ symbol: 'EICHERMOT.NS', name: 'Eicher Motors' },
	{ symbol: 'HEROMOTOCO.NS', name: 'Hero MotoCorp' },
	{ symbol: 'BRITANNIA.NS', name: 'Britannia' },
	{ symbol: 'CIPLA.NS', name: 'Cipla' },
	{ symbol: 'GRASIM.NS', name: 'Grasim' },
	{ symbol: 'HINDALCO.NS', name: 'Hindalco' },
	{ symbol: 'INDUSINDBK.NS', name: 'IndusInd Bank' },
	{ symbol: 'SHREECEM.NS', name: 'Shree Cement' },
	{ symbol: 'SBILIFE.NS', name: 'SBI Life' },
	{ symbol: 'HDFCLIFE.NS', name: 'HDFC Life' },
	{ symbol: 'DIVISLAB.NS', name: "Divi's Labs" },
	{ symbol: 'LTIM.NS', name: 'LTIMindtree' },
	{ symbol: 'BEL.NS', name: 'BEL' }
];
